

before_script:
  - docker info
  - apk add --no-cache curl

build_image:
  tags:
    - deployed
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - DOCKER_BUILDKIT=1 docker build -t $CI_REGISTRY/$CI_REGISTRY_USER/accordee-frontend .
    - docker push $CI_REGISTRY/$CI_REGISTRY_USER/accordee-frontend
    - curl -X POST http://192.168.1.110:9000/api/webhooks/d5cca057-f748-44e8-9b72-813fe22f990a